name: Test String Utility Functions

on:
    push:
        branches:
          - development

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
            with:
              ref: development
              

          - name: Set ip python
            uses: actions/setup-python@v2
            with:
                python-version: 3.12

        #   - name: Install Dependencies
        #     run: pip install -r requirements.txt

          - name: Run Tests
            run: python runTests.py

          - name: Checkout main branch
            uses: actions/checkout@v2
            with:
              ref: main

          - name: Merge to main if tests pass
            if: ${{ success() }}
            run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub Actions"
                git merge origin/development --no-f --no-commit
                git commit -m "Merge development branch"
                git push origin main
